-- skill_icons.lua — skill name -> game icon base name. Rendered as Game\ui\icon\<name>.dds.
-- Sourced from aa-classic.com/skillcalc (Spellsong: Sorcery / Songcraft / Auramancy).
-- Extend by pasting more name="icon_skill_x" pairs from the skillcalc DOM.
local S = {
    -- Sorcery
    ["Flamebolt"]            = "icon_skill_magic01",
    ["Freezing Arrow"]       = "icon_skill_magic04",
    ["Insulating Lens"]      = "icon_skill_magic02",
    ["Arc Lightning"]        = "icon_skill_magic05",
    ["Freezing Earth"]       = "icon_skill_magic10",
    ["Searing Rain"]         = "icon_skill_magic16",
    ["Frigid Tracks"]        = "icon_skill_magic06",
    ["Magic Circle"]         = "icon_skill_magic15",
    ["Chain Lightning"]      = "icon_skill_magic19",
    ["Flame Barrier"]        = "icon_skill_magic22",
    ["Meteor Strike"]        = "icon_skill_magic13",
    ["Gods' Whip"]           = "icon_skill_magic26",
    ["Void Leap"]            = "icon_skill_hatred24",
    ["Rising Hatred"]        = "icon_skill_hatred02",
    ["Serpent Strike"]       = "icon_skill_hatred25",
    ["Mana Pool Increase"]   = "icon_skill_magic03",
    ["Magic Range Boost"]    = "icon_skill_magic18",
    ["Efficient Sorcery"]    = "icon_skill_magic21",
    ["Mana Flurry"]          = "icon_skill_magic31",
    ["Recuperation"]         = "icon_skill_magic32",
    ["Magic Precision"]      = "icon_skill_magic20",
    ["Aranzeb's Infusion"]   = "icon_skill_magic25",
    -- Songcraft
    ["Critical Discord"]     = "icon_skill_romance14",
    ["Startling Strain"]     = "icon_skill_romance15",
    ["Quickstep"]            = "icon_skill_romance02",
    ["Dissonance"]           = "icon_skill_romance17",
    ["Healing Hymn"]         = "icon_skill_romance29",
    ["Hummingbird Ditty"]    = "icon_skill_romance01",
    ["Ode to Recovery"]      = "icon_skill_romance05",
    ["Rhythmic Renewal"]     = "icon_skill_romance26",
    ["Bulwark Ballad"]       = "icon_skill_romance19",
    ["Bloody Chantey"]       = "icon_skill_romance08",
    ["Alarm Call"]           = "icon_skill_romance25",
    ["Grief's Cadence"]      = "icon_skill_romance30",
    ["Abyssal Echoes"]       = "icon_skill_hatred29",
    ["Polymorphic Resonance"]= "icon_skill_hatred30",
    ["Syncopation"]          = "icon_skill_magic09",
    ["Hold the Note"]        = "icon_skill_romance28",
    ["Uptempo"]              = "icon_skill_romance16",
    ["Disciplined Performance"]= "icon_skill_romance31",
    ["Loudspeaker"]          = "icon_skill_romance18",
    ["Allegretto"]           = "icon_skill_romance32",
    ["Zeal"]                 = "icon_skill_romance03",
    -- Auramancy
    ["Thwart"]               = "icon_skill_will24",
    ["Comet's Boon"]         = "icon_skill_will01",
    ["Spell Shield"]         = "icon_skill_will14",
    ["Vicious Implosion"]    = "icon_skill_will04",
    ["Teleportation"]        = "icon_skill_will11",
    ["Health Lift"]          = "icon_skill_will21",
    ["Meditate"]             = "icon_skill_will05",
    ["Shrug It Off"]         = "icon_skill_will12",
    ["Liberation"]           = "icon_skill_will08",
    ["Leech"]                = "icon_skill_will07",
    ["Protective Wings"]     = "icon_skill_will13",
    ["Mirror Warp"]          = "icon_skill_will27",
    ["Crushing Grasp"]       = "icon_skill_hatred14",
    ["Abyssal Wave"]         = "icon_skill_hatred13",
    ["Absorb Damage"]        = "icon_skill_will02",
    ["Hearten"]              = "icon_skill_buff43",
    ["Inspiration Cloak"]    = "icon_skill_will28",
    ["Unassailable"]         = "icon_skill_will17",
    ["Improved Targeting"]   = "icon_skill_will19",
    ["Magic Condenser"]      = "icon_skill_will29",
    ["Teleportation Discipline"] = "icon_skill_will16",
    -- Battlerage
    ["Triple Slash"]         = "icon_skill_fight02",
    ["Charge"]               = "icon_skill_fight14",
    ["Whirlwind Slash"]      = "icon_skill_fight09",
    ["Sunder Earth"]         = "icon_skill_fight04",
    ["Lasso"]                = "icon_skill_fight19",
    ["Terrifying Roar"]      = "icon_skill_fight26",
    ["Bondbreaker"]          = "icon_skill_fight16",
    ["Precision Strike"]     = "icon_skill_fight15",
    ["Frenzy"]               = "icon_skill_fight10",
    ["Battle Focus"]         = "icon_skill_fight08",
    ["Tiger Strike"]         = "icon_skill_fight18",
    ["Behind Enemy Lines"]   = "icon_skill_fight28",
    ["Soulbound Blades"]     = "icon_skill_hatred05",
    ["Swordfall"]            = "icon_skill_hatred04",
    ["Weapon Maneuvers"]     = "icon_skill_fight03",
    ["Dual-Wield Proficiency"] = "icon_skill_fight20",
    ["Attack Speed Training"]= "icon_skill_fight17",
    ["Deflect and Retaliate"]= "icon_skill_fight23",
    ["Reckless Charge"]      = "icon_skill_fight29",
    ["Puncture"]             = "icon_skill_fight24",
    ["Weapon Mastery"]       = "icon_skill_fight30",
    -- Witchcraft
    ["Earthen Grip"]         = "icon_skill_illusion09",
    ["Enervate"]             = "icon_skill_illusion03",
    ["Bubble Trap"]          = "icon_skill_illusion04",
    ["Insidious Whisper"]    = "icon_skill_illusion05",
    ["Purge"]                = "icon_skill_illusion14",
    ["Play Dead"]            = "icon_skill_illusion07",
    ["Courageous Action"]    = "icon_skill_illusion08",
    ["Lassitude"]            = "icon_skill_illusion01",
    ["Banshee Wail"]         = "icon_skill_illusion18",
    ["Focal Concussion"]     = "icon_skill_illusion11",
    ["Dahuta's Breath"]      = "icon_skill_illusion22",
    ["Fiend's Knell"]        = "icon_skill_illusion24",
    ["Devour Hope"]          = "icon_skill_hatred07",
    ["Stonesight"]           = "icon_skill_hatred08",
    ["Folding Time"]         = "icon_skill_illusion02",
    ["Illusion's Favor"]     = "icon_skill_illusion25",
    ["Magic Detection"]      = "icon_skill_illusion15",
    ["Mitigation"]           = "icon_skill_illusion23",
    ["Baleful Recharge"]     = "icon_skill_illusion17",
    ["Augment Witchcraft"]   = "icon_skill_illusion20",
    ["Enshroud"]             = "icon_skill_illusion26",
    -- Defense
    ["Shield Slam"]          = "icon_skill_adamant01",
    ["Refreshment"]          = "icon_skill_adamant02",
    ["Bull Rush"]            = "icon_skill_adamant28",
    ["Boastful Roar"]        = "icon_skill_adamant27",
    ["Toughen"]              = "icon_skill_adamant06",
    ["Revitalizing Cheer"]   = "icon_skill_adamant14",
    ["Redoubt"]              = "icon_skill_adamant05",
    ["Ollo's Hammer"]        = "icon_skill_will26",
    ["Mocking Howl"]         = "icon_skill_adamant07",
    ["Imprison"]             = "icon_skill_love10",
    ["Invincibility"]        = "icon_skill_streak16",
    ["Fortress"]             = "icon_skill_adamant29",
    ["Shield Throw"]         = "icon_skill_hatred10",
    ["Cruel Binding"]        = "icon_skill_hatred11",
    ["Supplemental Block"]   = "icon_skill_adamant15",
    ["Shield Edge"]          = "icon_skill_adamant04",
    ["Shield of Steel"]      = "icon_skill_adamant30",
    ["Guardian"]             = "icon_skill_adamant20",
    ["Spry Fortress"]        = "icon_skill_adamant31",
    ["Bear's Vigor"]         = "icon_skill_adamant26",
    ["Ursine Roar"]          = "icon_skill_adamant32",
    -- Archery
    ["Charged Bolt"]         = "icon_skill_wild02",
    ["Piercing Shot"]        = "icon_skill_vocation01",
    ["Endless Arrows"]       = "icon_skill_vocation25",
    ["Double Recurve"]       = "icon_skill_wild08",
    ["Deadeye"]              = "icon_skill_wild21",
    ["Snare"]                = "icon_skill_wild14",
    ["Float"]                = "icon_skill_wild05",
    ["Boneyard"]             = "icon_skill_magic24",
    ["Concussive Arrow"]     = "icon_skill_wild15",
    ["Missile Rain"]         = "icon_skill_wild10",
    ["Intensity"]            = "icon_skill_wild09",
    ["Snipe"]                = "icon_skill_wild24",
    ["Serpent's Sight"]      = "icon_skill_hatred20",
    ["Hunting Pack"]         = "icon_skill_hatred22",
    ["Wild Instincts"]       = "icon_skill_wild03",
    ["Eagle Eyes"]           = "icon_skill_wild25",
    ["Archery Expertise"]    = "icon_skill_wild16",
    ["Evasion"]              = "icon_skill_wild11",
    ["Marksman"]             = "icon_skill_wild19",
    ["Sharpshooting"]        = "icon_skill_wild07",
    ["Feral Claws"]          = "icon_skill_wild26",
    -- Shadowplay
    ["Rapid Strike"]         = "icon_skill_vocation23",
    ["Overwhelm"]            = "icon_skill_vocation07",
    ["Drop Back"]            = "icon_skill_vocation15",
    ["Wallop"]               = "icon_skill_vocation27",
    ["Stalker's Mark"]       = "icon_skill_wild17",
    ["Stealth"]              = "icon_skill_vocation05",
    ["Toxic Shot"]           = "icon_skill_wild01",
    ["Pin Down"]             = "icon_skill_vocation18",
    ["Shadowsmite"]          = "icon_skill_vocation06",
    ["Freerunner"]           = "icon_skill_vocation11",
    ["Shadow Step"]          = "icon_skill_vocation16",
    ["Throw Dagger"]         = "icon_skill_vocation28",
    ["Venom Blades"]         = "icon_skill_hatred27",
    ["Assassination"]        = "icon_skill_hatred38",
    ["Evasive Counterstrike"]= "icon_skill_vocation04",
    ["Consecutive Evasion"]  = "icon_skill_vocation08",
    ["Disregard"]            = "icon_skill_vocation17",
    ["Loophole"]             = "icon_skill_vocation29",
    ["Piercing"]             = "icon_skill_vocation12",
    ["Bloodthirst Intensified"] = "icon_skill_buff66",
    ["Shadow Mastery"]       = "icon_skill_vocation30",
    -- Occultism
    ["Mana Stars"]           = "icon_skill_death25",
    ["Mana Force"]           = "icon_skill_death14",
    ["Hell Spear"]           = "icon_skill_death06",
    ["Absorb Lifeforce"]     = "icon_skill_death05",
    ["Summon Crows"]         = "icon_skill_death09",
    ["Crippling Mire"]       = "icon_skill_death11",
    ["Telekinesis"]          = "icon_skill_death10",
    ["Retribution"]          = "icon_skill_death02",
    ["Stillness"]            = "icon_skill_death07",
    ["Urgency"]              = "icon_skill_death03",
    ["Summon Wraith"]        = "icon_skill_death13",
    ["Death's Vengeance"]    = "icon_skill_death27",
    ["Cursed Thorns"]        = "icon_skill_hatred18",
    ["Shadow Circle"]        = "icon_skill_hatred16",
    ["Enhanced Mana Recovery"] = "icon_skill_death04",
    ["Reprisal"]             = "icon_skill_death08",
    ["Caster's Enrichment"]  = "icon_skill_death23",
    ["Macabre Reach"]        = "icon_skill_death28",
    ["Overpowered Spell Locus"] = "icon_skill_death24",
    ["Intensified Harm"]     = "icon_skill_death15",
    ["Death's Beckoning"]    = "icon_skill_death29",
    -- Vitalism
    ["Holy Bolt"]            = "icon_skill_love32",
    ["Mirror Light"]         = "icon_skill_love02",
    ["Antithesis"]           = "icon_skill_love01",
    ["Resurgence"]           = "icon_skill_love03",
    ["Revive"]               = "icon_skill_love06",
    ["Skewer"]               = "icon_skill_love05",
    ["Mend"]                 = "icon_skill_love07",
    ["Aranzeb's Boon"]       = "icon_skill_love28",
    ["Renewal"]              = "icon_skill_romance04",
    ["Fervent Healing"]      = "icon_skill_love21",
    ["Infuse"]               = "icon_skill_love27",
    ["Whirlwind's Blessing"] = "icon_skill_love29",
    ["Abyssal Petrification"]= "icon_skill_hatred39",
    ["Defy Death"]           = "icon_skill_hatred33",
    ["Painful Recharge"]     = "icon_skill_love14",
    ["Quick Recovery"]       = "icon_skill_love04",
    ["Spirit Growth"]        = "icon_skill_love18",
    ["Alms"]                 = "icon_skill_love30",
    ["Invigorated Healing"]  = "icon_skill_love08",
    ["Defiance"]             = "icon_skill_love26",
    ["Joyous Spirit"]        = "icon_skill_love31",
    -- NB: "Rising Hatred" (icon_skill_hatred02) is shared across all abyssal trees; defined once above.
}

-- Songcraft instrument skills appear with a "[Perform] " prefix in the calc; the combat
-- log may use either form, so register both.
S["[Perform] Quickstep"]        = S["Quickstep"]
S["[Perform] Ode to Recovery"]  = S["Ode to Recovery"]
S["[Perform] Bulwark Ballad"]   = S["Bulwark Ballad"]
S["[Perform] Bloody Chantey"]   = S["Bloody Chantey"]
S["[Perform] Grief's Cadence"]  = S["Grief's Cadence"]

-- Basic Combat (auto-attacks). The combat log normalizes basic attacks to "Auto Attack"
-- and "Ranged Attack", so map those to the game's basic-combat icons (Melee Attack / Shoot
-- Arrow). Icons are icon_skill_basic01..13 + icon_skill_kick; which number is which is a
-- BEST GUESS (the skillcalc doesn't cover Basic Combat) -- if an auto-attack icon looks
-- wrong, change the number below.
S["Auto Attack"]   = "icon_skill_basic01"   -- Melee Attack
S["Ranged Attack"] = "icon_skill_basic03"   -- Shoot Arrow
S["Kick"]          = "icon_skill_kick"      -- confirmed (buff 6771)

-- (Removed the static "Meteor Strike -> magic39" bake — ancestral-variant DETECTION now handles
--  this dynamically per session; see skill_variants.lua + DetectAndLockVariant in main.lua.)

return S
