-- skill_damage_types.lua
-- Auto-generated by parse_skills.ps1 from aa-classic.com/skills/ JSON data.
-- Damage type determined by token in skill description:
--   #{detail_melee_damage}  -> "Melee"
--   #{detail_ranged_damage} -> "Ranged"
--   #{detail_spell_damage}  -> "Magic"
--   #{detail_heal_damage}   -> "Magic"

local SKILL_DAMAGE_TYPES = {

    -- ARCHERY
    ["Charged Bolt"] = "Ranged",
    ["Piercing Shot"] = "Ranged",
    ["Boneyard"] = "Ranged",
    ["Concussive Arrow"] = "Ranged",
    ["Missile Rain"] = "Ranged",
    ["Snipe"] = "Ranged",
    ["Hunting Pack"] = "Ranged",

    -- AURAMANCY
    ["Comet's Boon"] = "Magic",
    ["Vicious Implosion"] = "Magic",
    ["Crushing Grasp"] = "Magic",
    ["Abyssal Wave"] = "Magic",

    -- BATTLERAGE
    ["Triple Slash"] = "Melee",
    ["Charge"] = "Melee",
    ["Whirlwind Slash"] = "Melee",
    ["Sunder Earth"] = "Melee",
    ["Precision Strike"] = "Melee",
    ["Tiger Strike"] = "Melee",
    ["Behind Enemy Lines"] = "Melee",
    ["Swordfall"] = "Melee",

    -- DEFENSE
    ["Shield Slam"] = "Melee",
    ["Bull Rush"] = "Melee",
    ["Ollo's Hammer"] = "Melee",
    ["Shield Throw"] = "Melee",

    -- OCCULTISM
    ["Mana Stars"] = "Magic",
    ["Mana Force"] = "Magic",
    ["Hell Spear"] = "Magic",
    ["Absorb Lifeforce"] = "Magic",
    ["Summon Crows"] = "Magic",
    ["Crippling Mire"] = "Magic",
    ["Summon Wraith"] = "Magic",
    ["Death's Vengeance"] = "Magic",
    ["Cursed Thorns"] = "Magic",

    -- SHADOWPLAY
    ["Rapid Strike"] = "Melee",
    ["Overwhelm"] = "Melee",
    ["Wallop"] = "Melee",
    ["Stalker's Mark"] = "Ranged",
    ["Toxic Shot"] = "Ranged",
    ["Pin Down"] = "Melee",
    ["Throw Dagger"] = "Melee",
    ["Venom Blades"] = "Melee",

    -- SONGCRAFT
    ["Critical Discord"] = "Magic",
    ["Dissonance"] = "Magic",

    -- SORCERY
    ["Flamebolt"] = "Magic",
    ["Freezing Arrow"] = "Magic",
    ["Arc Lightning"] = "Magic",
    ["Freezing Earth"] = "Magic",
    ["Searing Rain"] = "Magic",
    ["Chain Lightning"] = "Magic",
    ["Flame Barrier"] = "Magic",
    ["Meteor Strike"] = "Magic",
    ["Gods' Whip"] = "Magic",
    ["Serpent Strike"] = "Magic",

    -- VITALISM
    ["Holy Bolt"] = "Magic",
    ["Antithesis"] = "Magic",
    ["Skewer"] = "Magic",
    ["Mend"] = "Magic",

    -- WITCHCRAFT
    ["Earthen Grip"] = "Magic",
    ["Enervate"] = "Magic",
    ["Focal Concussion"] = "Magic",
    ["Dahuta's Breath"] = "Magic",

    -- =========================================================
    -- SUPPLEMENTAL  (procs, DoTs, server-specific, ancestral variants)
    -- Not present in aa-classic.com JSON â€” maintained manually.
    -- =========================================================
    ["Shadowsmite"]        = "Melee",   -- uses #{charge_multiplier}, no damage token
    ["Hell Spears"]        = "Magic",   -- ancestral Occultism variant
    ["Blazing Arrow"]      = "Ranged",  -- server-specific / alternate
    ["Double Recurve"]     = "Ranged",  -- server-specific / alternate
    ["Malicious Binding"]  = "Magic",   -- Malediction (custom server content)
    ["Crashing Waves"]     = "Magic",
    ["Serpent Glare"]      = "Magic",
    ["Blazing Ward"]       = "Magic",
    ["Electric Shock"]     = "Magic",   -- proc / DoT tick source (inflicted by Arc Lightning)
    ["Venom"]              = "Magic",   -- DoT debuff name (appears as skill source)
    ["Bleeding"]           = "Magic",   -- DoT debuff name
}

return SKILL_DAMAGE_TYPES
